import config from '../../config/config-APP_TARGET'

export const PAGE_LOGIN = 'login'
export const PAGE_REGISTER = 'register'
export const PAGE_MAIN = 'main'

export const ACTION_SET_PAGE = 'ACTION_SHOW_LOGIN'

export const ACTION_LOGIN = 'ACTION_LOGIN'
export const ACTION_LOGIN_SUCCESS = 'ACTION_LOGIN_SUCCESS'
export const ACTION_LOGIN_FAIL = 'ACTION_LOGIN_FAIL'

export const ACTION_LOGOUT = 'ACTION_LOGOUT'
export const ACTION_LOGOUT_SUCCESS = 'ACTION_LOGOUT_SUCCESS'
export const ACTION_LOGOUT_FAIL = 'ACTION_LOGOUT_FAIL'

export const ACTION_CHECK_LOGIN = 'ACTION_CHECK_LOGIN'
export const ACTION_CHECK_LOGIN_SUCCESS = 'ACTION_CHECK_LOGIN_SUCCESS'
export const ACTION_CHECK_LOGIN_FAIL = 'ACTION_CHECK_LOGIN_FAIL'

export const ACTION_REGISTER = 'ACTION_REGISTER'
export const ACTION_REGISTER_SUCCESS = 'ACTION_REGISTER_SUCCESS'
export const ACTION_REGISTER_FAIL = 'ACTION_REGISTER_FAIL'

export const BASE_URL = config.api_url
